export { getPassageiro } from './passageiro/getPassageiro.api'
export { getCorridasPassageiro } from './corrida/getCorridasPassageiro.api'
export { alterarPassageiro } from './passageiro/alterarPassageiro.api'
export { axiosInstance } from "./_base/axios.instance";
export { criaPassageiro } from "./usuario/cria-passageiro.api";
export { criaMotorista } from "./usuario/cria-motorista.api";
export { buscaListaMotoristas } from "./motorista/lista-motorista.api"
export { getCorridasMotorista } from "./corrida/get-corridas-motorista.api"
export { getDetalhesCorrida } from "./corrida/get-detalhes-corrida.api"
export { putAvaliaMotorista } from "./avaliacao/put-avalia-motorista.api"
export { putAvaliaPassageiro } from "./avaliacao/put-avalia-passageiro.api"
export { putIniciaCorrida } from "./corrida/put-inicia-corrida.api"
export { putFinalizaCorrida } from "./corrida/put-finaliza-corrida.api"
export { getListaPassageiros } from "./passageiro/get-lista-passageiros.api"
export { postSolicitaCorrida } from "./corrida/post-solicita-corrida.api"
export { postVeiculo } from "./veiculo/cria-veiculo.api"
export { buscaListaPassageiros } from './passageiro/lista-passageiro.api'
export { depositar } from './passageiro/depositar.api'
export { saque } from './motorista/saque.api' 
export { getMotorista } from './motorista/get-motorista.api'
