DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS livro CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;


CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	senha VARCHAR(100) NOT NULL,
	ativo BOOLEAN NOT NULL
);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);


CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	funcao VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;


CREATE TABLE livro (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	situacao VARCHAR(50) NOT NULL,
	titulo VARCHAR(100) NOT NULL,
	data_inclusao DATE NOT NULL,
	data_devolucao DATE,
	usuario_id BIGINT
);
ALTER TABLE livro ADD CONSTRAINT pk_livro PRIMARY KEY (id);
ALTER TABLE livro ADD CONSTRAINT uk_livro UNIQUE (titulo);
ALTER TABLE livro ADD CONSTRAINT fk_livro_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;


insert into usuario (email, nome, senha, ativo) values ('admin@cwi.com.br', 'admin', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG', true);
insert into usuario (email, nome, senha, ativo) values ('usuario@cwi.com.br', 'usuario', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG', true);

insert into permissao (funcao, usuario_id) values ('ADMIN', 1);
insert into permissao (funcao, usuario_id) values ('USUARIO', 1);
insert into permissao (funcao, usuario_id) values ('USUARIO', 2);
