DROP TABLE IF EXISTS filme CASCADE;
CREATE TABLE filme (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   titulo VARCHAR(100) NOT NULL,
	descricao VARCHAR(500) NOT NULL,
	disponivel BOOLEAN NOT NULL,
	categoria VARCHAR(20) NOT NULL,
   responsavel VARCHAR(100),
	data_retirada DATE,
	imagem VARCHAR(500),
   CONSTRAINT pk_pet PRIMARY KEY (id),
	CONSTRAINT ck_filme_categoria CHECK (categoria in ('BRONZE', 'PRATA', 'OURO'))
);

